### ISSUE TITLE
Dirección cloudfront

### ISSUE THREAD

**Issue by janoonaj** [martjanz/precios-claros#3]
Hola,

muchas gracias por los scripts.

Una pregunta, si no te importa, ¿es tuyo el servicio https://d3e6htiiul5ek9.cloudfront.net/dev?

¿Es un servicio abierto por precios-claros? En caso de caerse, ¿sería posible realojarlo?

Muchas gracias

**Comment by martjanz** [comment]
Hola. No es mío, es el servicio de Precios Claros. Por lo que probé ahora pusieron quotas y este script se corta después de levantar algunos precios. Habría que adaptarlo para estas nuevas quotas.
